CREATE TABLE Users (
    UserID INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    CreatedAt DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    PasswordHash NVARCHAR(256) NULL
);
