CREATE TABLE Documents(
    DocumentID INT IDENTITY(1,1) PRIMARY KEY,
    PatientID INT FOREIGN KEY REFERENCES Patients(PatientID),
    FileName NVARCHAR(100),
    FileType NVARCHAR(100),
    FilePath NVARCHAR(255),
    UploadedBy INT FOREIGN KEY REFERENCES Users(UserID),
    UploadDate DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()
);
