CREATE TABLE MedicationLog(
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    MedicationID INT FOREIGN KEY REFERENCES Medications(MedID),
    Action NVARCHAR(50),
    ActionDate DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    PerformedBy INT FOREIGN KEY REFERENCES Users(UserID),
    Notes NVARCHAR(200)
);
