CREATE TABLE AuthSessions (
    SessionID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    LoginTime DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
    LogoutTime DATETIMEOFFSET NULL,
    IPAddress NVARCHAR(20),
    DeviceInfo NVARCHAR(200)
);