CREATE TABLE AuditLog (
    LogID INT IDENTITY(1,1) PRIMARY KEY,
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    Action NVARCHAR(100),
    TargetTable NVARCHAR(50),
    TargetID INT,
    Timestamp DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET()  
);
